Test project

diff --git a/.github/workflows/test2.yml b/.github/workflows/test2.yml
--- a/.github/workflows/test2.yml
+++ b/.github/workflows/test2.yml
@@ -1,4 +1,4 @@
-name: Test action failure
+name: Test project
 
 on:
   workflow_dispatch:
@@ -7,7 +7,7 @@ jobs:
   do_ocp:
     runs-on: ubuntu-latest
     env:
-      OCP_PROJECT_NAME: iankwatts-toolsX
+      OCP_PROJECT_NAME: iankwatts-tools
     steps:
       - name: OCP login
         run: |
@@ -15,10 +15,18 @@ jobs:
           oc login --token=${{ secrets.OPENSHIFT_TOKEN }} --server=${{ secrets.OPENSHIFT_URL }}
           oc project ${{ env.OCP_PROJECT_NAME }}
 
-      - name: Debug
-        if: ${{ failure() }}
-        run: echo "Error - exiting" && exit 1
+      #- name: Debug
+      #  if: ${{ failure() }}
+      #  run: echo "Error - exiting" && exit 1
+
+      - name: Project check
+        run: |
+          echo "::set-output name=oc-project::$(oc project)"
+        id: oc-project
         
+      - name: Debug
+        run: echo "--> ${{ env.oc-project }}"
+
       - name: Okay
         run: echo "Okay"
 
